In [4]:
import numpy as np

In [6]:
A = np.array([[1, 0, 2], [3, 1, 2], [1, 2, 2]])
b = np.transpose(np.array([1, -2, 1]))
c = np.transpose(np.ones(3))

***
<h4> 11 a. Evaluate A<sup>-1</sup>  </h4>


In [9]:
InvA = np.linalg.inv(A)

In [11]:
InvA

array([[-0.25 ,  0.5  , -0.25 ],
       [-0.5  ,  0.   ,  0.5  ],
       [ 0.625, -0.25 ,  0.125]])

***
<h4> 11 b. Computing A<sup>-1</sup> b </h4>


In [14]:
# InvA * b 
print(InvA * b)

[[-0.25  -1.    -0.25 ]
 [-0.5   -0.     0.5  ]
 [ 0.625  0.5    0.125]]


***
<h4> 11 b. Computing A<sup>-1</sup> c </h4>


In [17]:
# A * c 
print(A * c)

[[1. 0. 2.]
 [3. 1. 2.]
 [1. 2. 2.]]
